### ISSUE TITLE
bioExp-1 SolarPanel is broken

### ISSUE THREAD

**Issue by Olympic1** [VigilanteInc/BioMass#12]
When a greenhouse is deployed and has sunlight, it produces the resource "Light". This is not the case by the bioExp-1 (or EBC-1), but it has the exact same MODULE as a greenhouse.

But is it necessary that an experiment needs Light that does nothing with it? Same for storing resources in an experiment.

**Comment by VigilanteInc** [comment]
I think that part is still in development, but yes it should have the solar panel for the experiment that  Sean is designing for it. There will be a little more too it than opening the doors ??? SCIENCE! It will have to gather light first to generate science.

**Comment by Olympic1** [comment]
That will be a cool feature for it, I just found it weird that it had a solarpanel module but didn't work.

Closing this then because it's a WIP
